name       : libglu
version    : 9.0.0
release    : 6
source     :
    - https://mesa.freedesktop.org/archive/glu/glu-9.0.0.tar.gz : 4387476a1933f36fec1531178ea204057bbeb04cc2d8396c9ea32720a1f7e264
license    : SGI-B-1.0
component  : xorg.display
summary    : Mesa OpenGL Utility Library
builddeps  :
    - pkgconfig(gl)
    - pkgconfig32(gl)
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
description: |
    Mesa OpenGL Utility Library
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
    %make clean
