name       : libglu
version    : 9.0.2
release    : 9
source     :
    - https://archive.mesa3d.org/glu/glu-9.0.2.tar.xz : 6e7280ff585c6a1d9dfcdf2fca489251634b3377bfc33c29e4002466a38d02d4
license    : SGI-B-1.0
component  : xorg.display
summary    : Mesa OpenGL Utility Library
builddeps  :
    - pkgconfig(gl)
    - pkgconfig32(gl)
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
description: |
    Mesa OpenGL Utility Library
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
