name       : libglu
version    : 9.0.1
release    : 8
source     :
    - https://mesa.freedesktop.org/archive/glu/glu-9.0.1.tar.xz : fb5a4c2dd6ba6d1c21ab7c05129b0769544e1d68e1e3b0ffecb18e73c93055bc
license    : SGI-B-1.0
component  : xorg.display
summary    : Mesa OpenGL Utility Library
builddeps  :
    - pkgconfig(gl)
    - pkgconfig32(gl)
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
description: |
    Mesa OpenGL Utility Library
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
    %make clean
